from .h3_temporal_tile import (
    NODE_CLASS_MAPPINGS as _TILE_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _TILE_DISPLAY,
)
from .h3_latent_cache import (
    NODE_CLASS_MAPPINGS as _CACHE_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _CACHE_DISPLAY,
)

NODE_CLASS_MAPPINGS = {**_TILE_CLASS, **_CACHE_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_TILE_DISPLAY, **_CACHE_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
